export default {
    IC_KINO: require('./imageFile/ic_kino.png'),
    IC_HOME: require('./imageFile/ic_home.png'),
    IC_SURFING: require('./imageFile/ic_surfing.png'),
    IC_HULA: require('./imageFile/ic_hula.png'),
    IC_VULCANO: require('./imageFile/ic_vulcano.png'),
    IC_SEARCH: require('./imageFile/ic_search.png'),
    IMG_ERROR: require('./imageFile/img_error.png'),
    IC_ALOHA: require('./imageFile/ic_aloha.png'),
    IMG_HOME: require('./imageFile/img_home.png'),
    IMG_USER: require('./imageFile/img_user.jpg'),
    IMG_HIGHLIGHT_1: require('./imageFile/img_highlight_1.png'),
    IMG_HIGHLIGHT_2: require('./imageFile/img_highlight_2.png'),
    IMG_HIGHLIGHT_3: require('./imageFile/img_highlight_3.png'),
    IMG_SPOT_1: require('./imageFile/img_spot_1.png'),
    IMG_SPOT_2: require('./imageFile/img_spot_2.png'),
    IMG_SPOT_3: require('./imageFile/img_spot_3.png'),
    IC_BACK: require('./imageFile/ic_back.png'),
    IC_BACK_2: require('./imageFile/ic_back_2.png'),
    IMG_SURFING: require('./imageFile/img_surfing.png'),
};
